BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `TeamWork` (
	`TeamID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`TeamName`	TEXT NOT NULL,
	`TeamNumber`	INTEGER NOT NULL,
	`StudentID`	TEXT NOT NULL UNIQUE,
	FOREIGN KEY (StudentID) REFERENCES Students(StdentID)
);

CREATE TABLE IF NOT EXISTS `Students` (
	`StudentID`	TEXT NOT NULL UNIQUE,
	`StudentName`	TEXT NOT NULL,
	`CourseID`	TEXT NOT NULL UNIQUE,
	PRIMARY KEY(`StudentID`)
	FOREIGN KEY (CourseID) REFERENCES NovelTech(CourseID)
);
CREATE TABLE IF NOT EXISTS `NovelTech` (
	`CourseID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`CourseTitle`	TEXT NOT NULL,
	`StudentID`	TEXT NOT NULL,
	`CourseCode`	TEXT NOT NULL,
	`TeamID`	INTEGER,
	FOREIGN KEY (TeamID) REFERENCES TeamWork(TeamID),
	FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
);

COMMIT;
